Electric-Coin-Company/zcash-android-wallet-sdk

src/main/proto/WalletData.proto, src/main/proto/compact_formats.proto, src/main/proto/service.proto
Motivation.
proto-swift-gen script adds the package prefix on a snake case fashion to Swift Struct files. 
This makes the code difficult to read and has no convenience to us.
Example:
`CompactBlock` -> `Cash_Z_Wallet_SDK_RPC_CompactBlock`
When adding `option swift_prefix = "";` the resulting struct Name is `CompactBlock`
=> add empty swift_prefix option value to .proto files

build.gradle, samples/memo/app/src/main/java/cash/z/wallet/sdk/sample/memo/Injection.kt, src/androidTest/java/cash/z/wallet/sdk/db/GlueIntegrationTest.kt, src/androidTest/java/cash/z/wallet/sdk/db/GlueSetupIntegrationTest.kt, src/androidTest/java/cash/z/wallet/sdk/db/IntegrationTest.kt, src/androidTest/java/cash/z/wallet/sdk/jni/RustBackendTest.kt, src/androidTest/java/cash/z/wallet/sdk/util/AddressGeneratorUtil.kt, src/androidTest/java/cash/z/wallet/sdk/util/BalancePrinterUtil.kt, src/main/java/cash/z/wallet/sdk/block/CompactBlockDbStore.kt, src/main/java/cash/z/wallet/sdk/block/CompactBlockDownloader.kt, src/main/java/cash/z/wallet/sdk/block/CompactBlockProcessor.kt, src/main/java/cash/z/wallet/sdk/block/CompactBlockStore.kt, src/main/java/cash/z/wallet/sdk/data/PersistentTransactionManager.kt, src/main/java/cash/z/wallet/sdk/data/SdkSynchronizer.kt, src/main/java/cash/z/wallet/sdk/data/SdkSynchronizerOld.kt, src/main/java/cash/z/wallet/sdk/db/CompactBlockDb.kt, src/main/java/cash/z/wallet/sdk/entity/CompactBlock.kt, src/main/java/cash/z/wallet/sdk/exception/Exceptions.kt, src/main/java/cash/z/wallet/sdk/ext/CurrencyFormatter.kt, src/main/java/cash/z/wallet/sdk/ext/WalletService.kt, src/main/java/cash/z/wallet/sdk/ext/ZcashSdk.kt, src/main/java/cash/z/wallet/sdk/jni/RustBackend.kt, src/main/java/cash/z/wallet/sdk/jni/RustBackendWelding.kt, src/main/java/cash/z/wallet/sdk/secure/Wallet.kt, src/main/java/cash/z/wallet/sdk/service/LightWalletGrpcService.kt, src/main/java/cash/z/wallet/sdk/service/LightWalletService.kt, src/test/java/cash/z/wallet/sdk/block/CompactBlockProcessorTest.kt
These changes largely reduce the amount of configuration that can be tweaked in order to prevent fragmentation of the anonymity set of users. If wallet makers change certain properties than it can become easy to detect which network requests are coming from which client. The goal is for clients to be as anonymous as possible.
=> Reduce configurability per Security Finding 1.

build.gradle, buildSrc/src/main/java/cash/z/ecc/android/Deps.kt
Previously, we just relied on implicit support given that x86 is compatible with both 32-bit and 64-bit systems but, going forward, the Play Store will reject these builds, EVEN FOR INTERAL TESTS. This addresses that but it comes with other considerations. arm64 and x86_64 are only supported on Android for API 21+. We probably should structure our resource folders differently to reflect this nuance. Our supported versions are: API 16+ for 32-bit hardware and API 21+ for 64-bit hardware, unless its 64-bit arm which is backward compatible with our 32-bit arm code. Clear as mud, right? I'll add this verbiage somewhere.
=> Added explicit support for x86_64

CHANGELOG.md, config.gradle, src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
When wallets have no received notes, finding the last transaction will fail so we should search in a way that returns null rather than an exception. 
_Note that the `receivedTransactions` flow is never null so the call to `first()` is fine but the call to `last()` needed to change._
=> Fix: Corrected logic when calculating birthdates

demo-app/src/main/AndroidManifest.xml, gradle.properties
Also resolve setting the main activity to exported, which is a new requirement for the new API level.
=> [#262] Target Android SDK 31

.run/clean.run.xml, README.md, docs/tests/Build.md, sdk-lib/build.gradle.kts
This resolves a regression from implementing #251.  Two different problems are fixed:
- The target API levels are set for 32-bit and 64-bit native libraries, preventing a build failure
- Rust build caches are purged, which masked this issue during testing
closes #290
closes #291
=> Fix rust build

CHANGELOG.md, MIGRATIONS.md, PUBLISHING.md, gradle.properties
We'll make the release from this branch, to skip the suspending API changes from going into this release.  Then we'll merge this to master to update the readme and other documentation.
=> Prepare 1.3.0-beta19 release

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml
This fixes a minor issue where the preflight check before a release deployment would fail, thus blocking the release deployment.
=> 380 fix release deployment

README.md, build-conventions/build.gradle.kts, build-conventions/src/main/kotlin/zcash-sdk.dependency-conventions.gradle.kts, docs/Setup.md
I made a similar change in the Secant repo last week.  https://github.com/zcash/secant-android-wallet/pull/548
This implementation is somewhat special from our other Gradle properties, because it does not get declared in the root gradle.properties.  The reason is that included builds are supposed to have their own properties e.g.
root_project/gradle.properties
root_project/build-conventions/gradle.properties
Instead of declaring the property in different places which might lead to confusion, this leaves the property undeclared, with the Gradle scripts assuming a default value of true.  The only time this is expected to be overridden is due to a workaround for an Android Studio bug.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it …
=> [#612] Make dependency locking configurable

lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/LightWalletClientImpl.kt
- We rather use add address method for this use case, as the addresses field does not  seem to be initialized with a fixed size at the time of address setting
- It does not produce the exception anymore
- Tested locally
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/941
> **Note**
[^2]: _While we aim for …
=> [#941] Fetch UTXOs setAddress() failure

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/WalletService.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1125.
> **Note** …
=> [#1125] Download Chain Tip

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SyncingResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ZcashSdk.kt
- Closes #1241
- The original solution came from the pseudocode requirement: _Download the blocks in `scan_range` into the block source, overwriting any existing blocks in this range._ Removed now.
- Closes #1243
- Closes #1222 as it was created to determine which failure type comes and don’t rewind for all of them
- Closes #1239 since it is the last required post-v2.0.0-rc1 cleanup.
- Rewind is done only when Continuity-error appears now. In case of other sync failures, the sync loop sleeps for a short time and then retries. Internal actions like fetching subtree roots, fetching chain tip, downloading, scanning, etc., still have their internal retry mechanisms.
- For the calculation of the rewind height, we use the existing `checkContinuityErrorResult` method, originally used only for …
=> [#1241][#1243][#1222] Rewinding when ContinuityError

backend-lib/src/main/rust/lib.rs, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
- Fixed the Rust FFI bug that caused us to be unable to catch the Continuity error
- Improved logging
- Moved handling the Continuity error to the outer synchronization loop, which works better with synchronization mutex
- Closes #1249
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual …
=> [#1249] Continuity error rewind

backend-lib/Cargo.lock, backend-lib/Cargo.toml
Closes #1268.
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might …
=> Migrate to Rust crate revision with spent UTXOs balance fix

.github/workflows/pull-request.yml
- The dual build part seems to be not necessary. Probably, we kept it longer than needed.
- Still, after the dual build is removed, the first build can take a longer time to finish. So the action timeout increased.
- Closes #1271 
- For reviewers: download the built Demo-app apks, install, and try its proper functionality: https://github.com/zcash/zcash-android-wallet-sdk/actions/runs/6310529332
> **Note**
[^1]: _Code often looks different …
=> [#1271] Remove double build (test)

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils.rs, backend-lib/src/main/rust/utils/exception.rs
In addition to the necessary breaking changes, we also clean up the style to match what is used in the `jni` crate examples.
> **Note** …
=> Migrate to `jni 0.21`

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummary.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/DarksideTestCoordinator.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/LightWalletClient.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/LightWalletClientImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/GetSubtreeRootsResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/AccountBalance.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/WalletSummary.kt
This improves performance in two ways:
- The `SdkSynchronizer` now reports balances of existing wallets and sync progress almost immediately, instead of after the first batch of blocks is scanned.
- In the steady state case, only a few subtree roots are downloaded, reducing the time until the first batch of blocks is scanned.
The transparent balance flow is now also refreshed from `WalletSummary`, instead of only showing the balance of the default transparent address. We now also treat the zero-conf balance as the full available transparent balance (as we already do when actually shielding it).
Closes Electric-Coin-Company/zcash-android-wallet-sdk#1310.
[^2]: _While we aim for …
=> Get `WalletSummary` on CBP start and use it to bound subtree roots

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
Downloading and scanning blocks are requirements for updating sync progress, but block deletion from the cache is not. This change moves block deletion into "the background" alongside transaction enhancement.
Closes #1360.
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you …
=> Emit sync progress from `CBP.runSyncingAndEnhancingOnRange` after scan

CHANGELOG.md, sdk-lib/proguard-consumer.txt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
=> [#1435] Eliminate logging with Proguard

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/RustLogging.kt, backend-lib/src/main/rust/lib.rs
- These changes bring the ability to easily change Rust layer trace-logs into the native SDK side. It does not provide it to the public API, though. That could be a possible follow-up. This is how the iOS SDK works right now, too.
- This closes #1479
- Eventually, this also closes #1466 
> **Note**
[^2]: _While we aim for …
=> [#1479] Customize Rust layer trace-level logs

.gitignore, CHANGELOG.md, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZatoshiExt.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecString.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecStringExt.kt, sdk-incubator-lib/src/main/res/values/strings-regex.xml
- Closes #1501
- Both ZecString and Zatoshi APIs now support MonetarySeparators with the same decimal and grouping characters by the grouping one omitting.
> **Note**
something during …
=> [#1501] Support same monetary separators

CHANGELOG.md, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/LightWalletClientImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt
- Use omitted `startHeight` in `LightWalletClientImpl.fetchUtxos`
- Throw `FetchUtxosException` from `CompactBlockProcessor.refreshUtxos` and handle it in its callers as we do with the other networking requests. The exception is then delivered to the public API using `onProcessorErrorHandler` or `onCriticalErrorHandler`
- These changes also remove the 9 attempt limit in `refreshUtxos`
- Closes #1539 
- Partly solves #683
> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
=> [#1539] Improve fetch UTXOs error handling

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/exchange/UsdExchangeRateFetcher.kt
=> Tor initialization and disposal

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
=> Fetch transaction error handling

sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZatoshiExt.kt
=> Currency conversion floating point hotfix

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TorClient.kt, backend-lib/src/main/rust/lib.rs
This was added to the `TorClient.dispose()` JNI pathway because that native coded did not require access to `JNIEnv` or `JClass`. However, it turns out that this annotation was only added in Android 8 for system usage [0], and was not CTS-tested public API until Android 14. For whatever reason, in API 27 (Android 8.1) the native method symbol can't be found, but in API 28 and above it can be.
The performance cost of regular JNI is no longer necessary to worry about given that we now keep a `TorClient` around long-term as part of `SdkSynchronizer`, so instead of doing anything complex to preserve it on API 28+ we just remove the `@CriticalNative` annotation and adjust the native method's signature to take (and ignore) the extra arguments.
Closes …
=> Remove `@CriticalNative` usage

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Navigation.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/send/view/SendView.kt, demo-app/src/main/res/values/strings.xml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManagerImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt
adds a transaction proposal API for URI strings
Closes #397
Add `proposeFulfillingPaymentUri` to changelog
> **Note**
[^3]: _While we …
=> [#397] Add ZIP 321 URI parser

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Derivation.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustDerivationTool.kt, backend-lib/src/main/rust/lib.rs, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/internal/DerivationToolImplTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt
=> Expose ZIP 32 arbitrary key derivation

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustDerivationTool.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils.rs
This fixes multiple JNI type signature inconsistencies, and cleans up argument handling on the Rust side to be less error-prone.
fixes #1657, fixes #1684
> **Note**
something during development of this pull …
=> JNI bugfixes

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Derivation.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/JniConstants.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustDerivationTool.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniMetadataKey.kt, backend-lib/src/main/rust/lib.rs, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountMetadataKey.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt
=> Add derivation methods for ZIP 325 private use metadata keys

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TorLwdConn.kt, backend-lib/src/main/rust/lib.rs
All other returns of a `jboolean` to indicate an error were removed in c78afc7d989bb74e1e375e38a62e472988495fe3.
fixes #1696
[^4]: _Having your code up to date and squashed will make it …
=> Remove the last `jboolean` error return from `backend-lib`

.github/actions/setup/action.yml
Error from CI:
```
info: installing component 'rustc'
1.67.1-x86_64-unknown-linux-gnu installed - rustc 1.67.1 (d5a82bbd2 2023-02-07)
info: checking for self-update
info: downloading self-update
warn: tool `rust-analyzer` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warn: tool `rustfmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warn: tool `cargo-fmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
info: using existing install for '1.67.1-x86_64-unknown-linux-gnu'
info: default toolchain set to '1.67.1-x86_64-unknown-linux-gnu'
1.67.1-x86_64-unknown-linux-gnu …
```
=> Use Rust 1.84.1 in `action.yml`

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
This changes the way how SDK internally calls `fetchUtxos`. It polls from height 0 instead of `fullyScannedHeight` to support Ledger funds rescue. cc @nuttycom  
> **Note**
something during development of this …
=> Fetch UTXOs from height 0 internally

backend-lib/src/main/rust/lib.rs
A scan progress of `0/0` means there are no shielded notes in the scan range. This is meant to be treated as 100%. However, on the Rust side of JNI a top-level filter was dropping the entire `WalletSummary` if the scan progress denominator was 0 (an artifact of an old approach that no longer applies). This went unnoticed until the recent Rust crate update, which included zcash/librustzcash#1773 making 0/0 occur at recovery start.
> **Note** …
=> Fix `WalletSummary` being returned as null
