README.md
Made changes to the README and removed some of the legacy warnings that were outdated to prepare this for the first versioned release.
=> Update README for first versioned release

Cargo.lock, Cargo.toml, src/main/java/cash/z/wallet/sdk/jni/RustBackend.kt, src/main/java/cash/z/wallet/sdk/jni/RustBackendWelding.kt, src/main/rust/lib.rs
Also updates the Rust dependencies.
=> RustBackend.decryptAndStoreTransaction()

docs/ci.md
Initial targets for CI stages.
We'll get more definition on the details once the goals look good.
=> Initial ci.md

ci/docker/Dockerfile, ci/tekton/zcash-android-sdk-cibundle.yml
This ran OK on the test cluster https://tekton-dashboard-dev.z.cash/#/namespaces/default/taskruns/zcash-android-sdk-cibundle-d6924
A few things could be improved, but it works!
=> Added tekton task for ciBuild run

docs/ci.md
Update the docs to reflect the new CI behavior.
=> Update ci.md to use labels

build.gradle, src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt, src/main/java/cash/z/ecc/android/sdk/ext/Twig.kt, src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt
Added the ExperimentalCoroutinesApi in build.grandle in order to clear some warning builds
=> Clear the warns build

README.md
Some grammar errors are fixed.
=> fix Readme grammar

README.md, samples/demo-app/README.md, samples/demo-app/app/src/main/java/cash/z/ecc/android/sdk/demoapp/MainActivity.kt, samples/demo-app/app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, samples/demo-app/app/src/main/res/drawable/ic_menu_balance.xml, samples/demo-app/app/src/main/res/layout/fragment_get_balance.xml, samples/demo-app/app/src/main/res/menu/activity_main_drawer.xml, samples/demo-app/app/src/main/res/navigation/mobile_navigation.xml, samples/demo-app/app/src/main/res/values/strings.xml
Created a new module called: Get Balance which shows the balance using from the viewingKey
=> Get balance

src/androidTest/java/cash/z/ecc/android/sdk/tool/SaplingParamToolTest.kt
I wrote unit tests required from this ticket:  #202
=> Unit test for param files

demo-app/src/main/AndroidManifest.xml, gradle.properties
Also resolve setting the main activity to exported, which is a new requirement for the new API level
=> [#262] Target Android SDK 31

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/App.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/StrictModeHelper.kt
This is similar to the strict mode change I added to the sample application.
Turning these on will help with fixing #269 as well as resolving a resource leak that I'm currently trying to track down.
=> [#268] Enable strict mode for demo-app

README.md, gradle/wrapper/gradle-wrapper.properties
In addition to updating the version of Gradle, I've added the sha256 to enable verification of the Gradle download
=> [#313] Gradle 7.3

.github/actions/setup/action.yml, .github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml, PUBLISHING.md, build-conventions/src/main/kotlin/zcash.dependency-conventions.gradle.kts, build.gradle.kts, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getblockrange/GetBlockRangeFragment.kt, docs/PUBLISHING.md, docs/ci.md, gradle.properties, sdk-lib/build.gradle.kts, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SaplingParamToolTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, settings.gradle.kts, tools/detekt-baseline.xml
The primary purpose of this is to set the stage for automated testing and deployment of snapshot releases to maven central, along with manual deployment of releases.  Most of the documentation on this process is in the commits.  The deployment is automatically disabled until the necessary credentials are added.
Addition of the detekt baseline allows detekt static analysis to also be run on each build.
=> GitHub Actions

.github/workflows/deploy-snapshot.yml
This is a fix for build failures seen here https://github.com/zcash/zcash-android-wallet-sdk/runs/4957504209?check_suite_focus=true
=> Bugfix for building snapshots on GitHub Actions

sdk-lib/build.gradle.kts
Attempt to resolve 400 error code from Maven Central in last CI snapshot deployment.
=> Fix version name for snapshot releases

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
=> [#387] Correct path for attaching library to CI results

.github/workflows/deploy-snapshot.yml
=> [#381] Automatically release snapshots

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
This is an attempt to fix release build deployments
=> Disabling signing for publishToMavenLocal

build.gradle.kts
This should fix publishing of our snapshots.  The last [CI build](https://github.com/zcash/zcash-android-wallet-sdk/runs/5066304732?check_suite_focus=true) returned this error:
```
* What went wrong:
Task 'closeAndReleaseRepository' not found in root project 'zcash-android-sdk'.
```
And this PR fixes it by making the publishing Gradle plugin available to the root build script.
=> Fix publishing

.github/workflows/pull-request.yml
This primarily moves the wildcard expansion from the shell to the zip command by escaping the asterisk from the shell command invocations.  This solves some issues with the test results not getting attached to the builds.
=> [#392] Fix collection of CI results

.github/workflows/pull-request.yml, demo-app/build.gradle.kts
The CI script already has an invocation for this, but the Gradle scripting needed wasn't implemented yet.  We didn't see the failure because the secrets for Firebase Test Lab aren't yet in place. This proactively should fix that once we have the Firebase Test Lab credentials.
=> [#394] Add robo test configuration

.github/actions/setup/action.yml, .github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml, gradle.properties
This implements the following enhancements:
- Improve build security by pinning GitHub Actions with a SHA instead of a tag
- Prevents potential OOM errors in Gradle
- Cancels redundant builds when a PR is being built and additional changes are pushed
=> Improve builds on GitHub Actions

gradle/wrapper/gradle-wrapper.properties
These minor changes update the current Gradle tool version from 7.4 to 7.4.1. as well as the Gradle distribution SHA-256 checksum.
=> [#429] Update Gradle version to 7.4.1.

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
I'm hoping this resolves the last of the maven deployment issues.  Due to the nature of these changes, we're sort of "testing in production" until it finally stabilizes.
=> [#430] Extend build timeout for deployment

.github/workflows/unwedge-maven-central.yml, docs/ci.md
=> [#434] Add workflow to unwedge Maven Central deployments

sdk-lib/build.gradle.kts
The maintainer of the Gradle plugin we use for Maven Publishing suggested this change.
=> Fix snapshot publishing

.github/actions/setup/action.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/unwedge-maven-central.yml
This primarily resolves the issue of our snapshot deployments timing out.  The call to closeAndRelease repository is not necessary for snapshot releases.
While I was updating the GitHub Actions configuration, I also fixed two other minor issues.  One was a naming typo and the other is a version bump for the cache action.
=> 444 snapshot timeout

CONTRIBUTING.md
Update that section of `CONTRIBUTING.md` to reflect the changes on iOS SDK
Closes #495
=> [#495] Update Contributing Guidelines "Commit Messages"

CHANGELOG.md, README.md
=> [#502] Prepare 1.4.0-beta01 release

gradle.properties
After the release of version 1.4.0-beta01 yesterday, this change prepares development for the next release. Snapshot deployments will be now versioned as 1.5.0-beta01.
=> Bump to version 1.5.0-beta01

CHANGELOG.md, sdk-lib/Cargo.lock, sdk-lib/Cargo.toml
This enables mobile wallets to send transactions after NU5 activation.
Part of #524.
=> Migrate to `zcash/librustzcash` revision with NU5 awareness

.github/actions/setup/action.yml, README.md
Temurin/Adoptium is the default used by Gradle toolchains, and they now have both Java 11 and 17 ARM support for Macs
=> [#517] Switch to Adoptium JDK

CHANGELOG.md, sdk-lib/Cargo.lock, sdk-lib/Cargo.toml, sdk-lib/src/main/rust/lib.rs
This doesn't affect Sapling note detection (which uses Compact Blocks),
but enables the enhancement logic to decrypt and store the corresponding
transactions for displaying memo fields.
=> Migrate to `zcash/librustzcash` revision with v5 tx parsing

CHANGELOG.md, docs/PUBLISHING.md, gradle.properties
=> [#523] Prepare for next release

CHANGELOG.md, sdk-lib/proguard-consumer.txt
=> [#537] Prevent R8 warnings for OkHttp

.github/workflows/deploy-snapshot.yml, docs/PUBLISHING.md
=> [#546] Rename default branch

.github/actions/setup/action.yml, .github/dependabot.yml, .github/workflows/pull-request.yml
=> GitHub actions updates

build-conventions/src/main/kotlin/zcash-sdk.rosetta-conventions.gradle.kts, build.gradle.kts
=> [#562] Detect and warn when running under Rosetta

.github/dependabot.yml
=> [#570] Run dependabot on Composite workflows

CHANGELOG.md, MIGRATIONS.md, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/DarksideTestCoordinator.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listtransactions/TransactionViewHolder.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listutxos/UtxoViewHolder.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/send/SendFragment.kt, gradle.properties, sdk-lib/build.gradle.kts, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/transaction/PersistentTransactionManagerTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/sample/ShieldFundsSample.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/sample/TransparentRestoreSample.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/db/entity/Transactions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ZcashSdk.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/PersistentTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackendWelding.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Zatoshi.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/type/WalletTypes.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/ZatoshiTest.kt, settings.gradle.kts
When implementing this, I started considering whether we could maintain the existing APIs and mark them as deprecated, then adding additional new methods that leverage Zatoshi.  However there are some places where this wouldn't be viable such as the WalletBalance object.  So I went ahead and decided we should just do the breaking API changes now.
=> [#477] Typesafe Zatoshi APIs for amounts

darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/DarksideTestPrerequisites.kt, gradle.properties
=> [#579] Compile with Android API 33

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDbStore.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockStore.kt
Honza, this is the fix for the crash you found testing the BlockHeight integration in the app.
=> [#606] Fix BlockHeight read from CompactBlockStore

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listtransactions/ListTransactionsFragment.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/DataDbScannerUtil.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Initializer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/Twig.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/CheckpointTool.kt
This includes a few different fixes that prevented the demo app and other SDK consumers from working.
First, initialization of the demo app was fixed to use the sapling activation height rather than the current latest checkpoint.
Second, CompactBlockProcessor wasn’t downloading blocks.
Third, a few potential thread safety issues were resolved by making fields that are accessed by multiple threads volatile.
=> [#610] Fix block download regression

sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ZcashSdk.kt
=> [#625] Reduce block batch size to fix OOM

demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getblockrange/GetBlockRangeFragment.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/SanityTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/db/entity/CompactBlockEntity.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDbStore.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockStore.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/CompactBlockDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/service/LightWalletGrpcService.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/service/LightWalletService.kt
This change leverages the gRPC streaming API along with the elimination of bulk inserts to SQLite to reduce the amount of memory required to write blocks.
=> [#629] Stream blocks during download

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
This should yield approximatly a 10% performance improvement, as it prevents downloading duplicate blocks.
=> [#628] Fix off-by-one download blocks

CHANGELOG.md, MIGRATIONS.md
This should have been done with the BlockHeight pull request, so I'm catch up and adding this now.
=> Update changelog for 1.8 release

gradle.properties
This ensures that further commits to the main branch deploy snapshots under the 1.9 version
=> Bump version to prepare for 1.9-beta01

.github/workflows/pull-request.yml, docs/Setup.md
=> [#597] Run unit tests on CI

gradle/wrapper/gradle-wrapper.properties
=> [#656] Gradle 7.5.1

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/691.
=> [#691] Increase Deploy action Upload artifacts timeout

sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SaplingParamToolTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/SaplingParamsFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ZcashSdk.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/SaplingParamTool.kt
- The new implementation limits the maximum sapling file size
- To have this fully working we need to continue with implementation https://github.com/zcash/zcash-android-wallet-sdk/issues/665
- Created also a tests for this new functionality, although we have these tests disabled for CI runs, we'll move them to a separate integration tests module soon and then these tests can be used.
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/664.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
=> [#664] Check sapling files size

docs/Setup.md
=> Clarify instructions for Android NDK installation.

sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/SanityTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/SmokeTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/jni/TransparentTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/AddressGeneratorUtil.kt
UFVKs and UAs contain Sapling and transparent receivers, corresponding to how keys are currently derived from mnemonic phrases in the wallet.
=> Update test vectors to use UFVKs and UAs as appropriate

gradle.properties
=> Bump version to 1.9.0-beta04

sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SaplingParamToolBasicTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SaplingParamToolIntegrationTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/SaplingParamTool.kt
This PR brings these two new functionalities:
- Auto re-run failed sapling parameters fetching
- Returning a new FetchParamsException or ValidateParamsException if anything failed in the file fetching phase. The exceptions hold parameters object for which the fetching failed, so it can be re-run manually.
The new functionalities are covered by a new integration tests.
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/665.
=> [#665] Recover from corrupted sapling-spend.params and sapling-output.params files

docs/Setup.md
=> added python installation instruction to Setup.md

sdk-lib/Cargo.lock, sdk-lib/Cargo.toml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackendWelding.kt, sdk-lib/src/main/rust/lib.rs, sdk-lib/src/main/rust/utils/exception.rs
=> More Rust updates

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/ReceivedNoteTable.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/ReceivedTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/SentNoteTable.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackendWelding.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
I understand the memo specification is more complex than displaying plain text in the UI. The goal of this change is to implement very straightforward access to memos for the purpose of getting our next SDK release based on how memos are used in the ECC Wallet UI.  I'm intentionally trying to avoid creating a model object representing memos in this PR, because I want more time to get such an API correct.
=> [#743] Add API for reading memos

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/MainActivity.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/SharedViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/home/HomeFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listtransactions/ListTransactionsFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listutxos/ListUtxosFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/send/SendFragment.kt, sdk-lib/schemas/cash.z.ecc.android.sdk.internal.db.pending.PendingTransactionDb/2.json, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/transaction/PersistentTransactionManagerTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/pending/PendingTransactionDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/pending/PendingTransactionEntity.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/PersistentTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/WalletTransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/LightWalletEndpointExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/PendingTransaction.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
I still need to do some manual testing, but I'd like to get the review process started.
=> [#748] Internal recipients for pending transactions

CHANGELOG.md, MIGRATIONS.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/SentNoteTable.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt
This adds another API, similar to the API for querying memos, to cover API removals due to the Roomoval.  I suspect that we'll refactor this further in the future.
I don't love that clients of the SDK need to make two additional queries (memos, recipients).  So a future enhancement will likely convert this into a single query that returns a stronger type safe object.  But until then this should bridge the API gap so we can complete the next SDK release.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …
=> 753 query recipients

sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
=> [#758] Add default alias for erase method

gradle.properties
I'm not updating the changelog just to avoid merge conflicts with the feature branch.  The beta05 release will just have updated checkpoints prior to 1.10.0-beta01 being released.
=> Bump version to 1.9.0-beta05

CHANGELOG.md, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listutxos/ListUtxosFragment.kt, docs/Setup.md, sdk-lib/Cargo.lock, sdk-lib/Cargo.toml, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/jni/TransparentTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackendWelding.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt, sdk-lib/src/main/rust/lib.rs, sdk-lib/src/main/rust/utils.rs
This pulls in the recent bugfixes to the Rust crates, removes FFI methods we don't need, and updates Rust dependencies.
=> More FFI updates

CHANGELOG.md, MIGRATIONS.md, gradle.properties, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> Update documentation for 1.10.0

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/res/layout/fragment_get_balance.xml, demo-app/src/main/res/values/strings.xml
=> [#763] Add shielding to demo app

sdk-lib/Cargo.lock, sdk-lib/Cargo.toml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/rust/lib.rs
ZIP 317 fee rules are disabled by default but exposed via a boolean flag.
=> Migrate to published Zcash Rust crates with ZIP 317 support

sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/pending/PendingTransactionDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/pending/PendingTransactionEntity.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/PendingTransaction.kt
This fixes a database migration issue with the PendingTransaction table.  Shielding is still broken due to another issue #780 but this moves things forward incrementally.
=> [#778] Fix PendingTransactionEntity crash

demo-app/build.gradle.kts, gradle.properties
=> [#786] Simplify signing during development

sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/UnifiedSpendingKey.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt
I went with the androidx annotation instead of a proguard-consumer.txt rule because the annotation is more likely to survive refactoring in the future.  The annotation is android-only, so if we move towards multiplatform then we might reconsider this at some point in the future.
=> [#723] Fix crash with minified release builds

sdk-lib/Cargo.lock, sdk-lib/Cargo.toml, sdk-lib/src/main/rust/lib.rs, sdk-lib/src/main/rust/utils.rs, sdk-lib/src/main/rust/utils/exception.rs, sdk-lib/src/main/rust/utils/target_ndk.rs, sdk-lib/src/main/rust/utils/trace.rs
This exposes any more structured `tracing` events that are logged within the Rust crates, while continuing to collect `log` records.
=> Use `tracing` crate for logs

.github/workflows/pull-request.yml, demo-app/build.gradle.kts, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/NativeLibraryLoader.kt
=> Fix JNI crash in demo app

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
=> [#811] Eliminate suspending function for sending/shielding

sdk-lib/Cargo.lock, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/NativeLibraryLoader.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/UnifiedSpendingKey.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt, sdk-lib/src/main/rust/lib.rs, sdk-lib/src/main/rust/utils/target_ndk.rs, sdk-lib/src/main/rust/utils/trace.rs
This enables the Rust logging backend by default, and disables most of the spans-to-events logic if Android tracing is disabled. It also updates to the newer Zcash Rust crate versions that include profiling spans for chain scanning.
=> Improve Rust profiling

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml
=> [#850] Use new API for build step outputs

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listtransactions/ListTransactionsFragment.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/855
=> [#855] Abandoned address property

sdk-lib/Cargo.lock
Closes zcash/zcash-android-wallet-sdk#824.
=> rust: cargo update

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/util/AndroidApiVersion.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/858.
=> [#858] No static field PREVIEW_SDK_INT

demo-app/build.gradle.kts, demo-app/proguard-project.txt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/862.
=> [#862] Disable logging with ProGuard for Demo-app

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml, docs/CI.md
This will make it easier for team members to find links to test results
I also extended the upload timeout because our last deployment hit a timeout trying to upload build artifacts.
=> [#881] Use variables for Test Lab

.github/workflows/pull-request.yml, CHANGELOG.md, gradle.properties, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/AllTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/ReceivedTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/SentTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Transaction.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> [#886] Support null block heights

sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/db/DatabaseCoordinatorTest.kt
- ~~RunTest API abandoned and RunBlocking used to be able to use delays in the test~~
- ~~As testing mutexes is not easy I prepared a test validation mechanism to decide if we should work with a particular test iteration result in the stress test or not~~
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/779.
=> [#779] Resolve flaky DatabaseCoordinatorTest

lightwallet-client-lib/build.gradle.kts
=> [#913] Change maven group for network module

CHANGELOG.md, build-conventions/src/main/kotlin/zcash-sdk.android-conventions.gradle.kts, build.gradle.kts, demo-app/build.gradle.kts, demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/test/UiTestPrerequisites.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Navigation.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/StrictModeHelper.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/util/AndroidApiVersion.kt, gradle.properties, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/service/ChangeServiceTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/DatabasePathFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/AndroidApiVersion.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/Files.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/ContextExt.kt
=> [#917] Min API 24

demo-app-benchmark-test/src/main/java/cash/z/ecc/android/sdk/demoapp/benchmark/StartupBenchmark.kt, demo-app-benchmark-test/src/main/java/cash/z/ecc/android/sdk/demoapp/benchmark/SyncBlockchainBenchmark.kt, demo-app/src/main/AndroidManifest.xml, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/MainActivity.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/SharedViewModel.kt, demo-app/src/main/res/menu/main.xml, demo-app/src/main/res/values/strings.xml, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt
=> [#924] Remove alias from WalletCoordinator

CHANGELOG.md, MIGRATIONS.md, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/BlockingLightWalletClient.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/CoroutineLightWalletClient.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/BlockingLightWalletClientImpl.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/CoroutineLightWalletClientImpl.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/jni/RustBackendWelding.kt, sdk-lib/src/main/rust/lib.rs
(eventually when it's done by a real Android developer) Closes #904
This Code is a Draft. I've ported the Rust code from Zcash-light-client-ffi repo to match JNIs rust FFI code so that should work.
The kotlin code is just a draft of how the fetchUtxos should be done instead. This will provide every derived transparent address for a specific account and fetch the corresponding UTXOs. if the caller is not rolling UAs, then the SDK will always request UTXOs for the legacy transparent address and the transparent receiver for the UA of diversifier index 0 for the account. 
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth …
=> List transparent receivers

.github/actions/setup/action.yml, docs/Setup.md
=> [#954] Install specific version of Rust

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
=> Increase CI build timeouts

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/pull-request.yml
=> Further increase build timeout

CHANGELOG.md, build.gradle.kts, demo-app/build.gradle.kts, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/StrictModeHelper.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/util/AndroidApiVersion.kt, gradle.properties, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/db/CommonDatabaseBuilderTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/db/NoBackupContextWrapperTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/AndroidApiVersion.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/DatabaseCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/ReadOnlySupportSqliteOpenHelper.kt
=> [#972] Min API 27

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/BlockBatch.kt
- Doubled fetching UTXOs and transparent balance updated at the beginning of the whole sync process after the app launch to fetch transparent transactions
- This fetch call will happen only once for the app living 
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1023.
> **Note**
[^2]: _While we aim for automated …
=> [#1023] Move Fetch UTXOs Before Block Sync

README.md
=> Remove ECC Wallet from readme

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt
- While solving this task, I found another strict mode violation, which was a bit more tricky to track down, but it seems to be caused by this [recent Android issue](https://github.com/aosp-mirror/platform_frameworks_base/commit/e7ae30f76788bcec4457c4e0b0c9cbff2cf892f3). Just filed follow up for it https://github.com/zcash/zcash-android-wallet-sdk/issues/1032.
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1031
> **Note** …
=> [#1031] StrictMode violation: LeakedClosableViolation data db

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/SdkDispatchers.kt, backend-lib/src/main/rust/lib.rs
=> rust: Name the Rayon threads

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/fixture/WalletSnapshotFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/AllTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/ClosedRangeExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/BlockBatch.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/BlockBatch.kt
- Tested with and analysed the related database entries with the Android Studio database inspector
- Measured its performance and it has no significant impact on the overall syncing process time
- Tested in parallel with the previous sync stages as well, but it does not give any significant improvement.
- Internal ENHANCING state eliminated as well, as described in https://github.com/zcash/zcash-android-wallet-sdk/issues/967
- We now treat the enhancing error as critical, as we do in case of other stages failures as well
- The enhancement range is changed in case of any previously un-enhanced transaction found in the transaction table view
- Changed enhancing trigger appropriately
- Covered also the case when the sync stage ended before the enhancement limit reached
- Cleaned up the code …
=> [#1026] Continuous Batched Enhancing

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt
Until we have more time to investigate, I propose reverting and reopening this issue due to a prelaunch report crash https://github.com/zcash/secant-android-wallet/issues/868
Once we get the SDK release deployed, we can circle back to this issue.
This reverts commit ca0e69d97f613fd781d4a9413616bcbbf7badeed.
> **Note**
[^2]: _While …
=> [#1031] Revert strictMode violation: LeakedClosableViolation data db

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1027, https://github.com/zcash/zcash-android-wallet-sdk/issues/1028
- Tested with setting a different wallet birthday height
- Implementation explanation inline
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If …
=> [#1027][#1028] CompactBlockProcessor Exception with off-by-one error

backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> zcash_client_sqlite 0.7.1

CHANGELOG.md
=> Update changelog for 1.17.0-beta01

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
- Enhancing transaction details mechanism was refactored to provide more clarity about its inner phases (fetching and decrypting with storing) and to be able to retry when the transaction fetching fails due to flaky network condition
- The retry mechanism copies the one used for downloading
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1039
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, …
=> [#1039] Retry enhancing transaction fetching 

CHANGELOG.md, demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getaddress/GetAddressFragment.kt, gradle.properties, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/939.
> **Note** …
=> [#939] Eliminate default arguments for Account

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt
=> [#940] Improve reliability of erasing SDK

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/BackendExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/BlockBatch.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/block/FileCompactBlockRepository.kt
- Functions of the Rust backend analyzed and some refactored to get rid of the dual success reporting system. Previously because of the common FFI layer for the iOS and Android SDK, the FFI replied with a boolean and by throwing RuntimeException together. We on Android reflected both in the Kotlin layer. This PR removes boolean reporting and preserves the reporting and handling with exceptions, as we mostly didn't work with the booleans at all.
- Some functions like `isValidSpendingKey`, `isValidShieldedAddress`, `isValidTransparentAddress`,  and `isValidUnifiedAddress` are preserved with the boolean reporting system, as it logically makes sense. 
- We'll continue with refactoring this further in the planned UniFFI replacement.
- Tested
- Closes …
=> [#920] Rust backend void return

.github/actions/setup/action.yml, .github/workflows/pull-request.yml, gradle.properties, settings.gradle.kts
By saving and restoring the cache at different times, this should improve performance by allowing the cache to be created during main branch builds and then just consumed by
=> [#877] Optimize CI build cache

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
- It replaces Long type usage with Kotlin Duration in the calculatePollInterval
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1048
> **Note**
something during development of this pull request, …
=> [#1048] Duration instead of Long

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/addresses/view/AddressesView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/balance/view/BalanceView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/send/view/SendView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transactions.kt
- With filed follow-up filed: Demo: Add Addresses and Transactions Compose Previews #1090.
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1088.
> **Note**
something during development of this …
=> [#1088] Demo: Add Missing Compose Previews

sdk-lib/src/main/java/cash/z/ecc/android/sdk/fixture/TransactionOverviewFixture.kt
- This just checks and validates the already existing TransactionOverview fixture.
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/953.
> **Note**
something during development of this pull …
=> [#953] TransactionOverview fixture

sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1099.
> **Note** …
=> [ #1099] Proper transaction state

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniSubtreeRoot.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/SubtreeRoot.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1123.
> **Note** …
=> [#1123] Linear vs Non-linear decision mechanism

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1130.
> **Note** …
=> [#1130] Initial Suggested Ranges Parsing

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/ExceptionExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/WalletService.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/BlockHeight.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/ext/ExceptionExtTest.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/BlockHeightTest.kt
- This improves internal state handling in CompactBlockProcessor. Error handling included. And it prepares us for ContinuityError handling too.
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1140 and https://github.com/zcash/zcash-android-wallet-sdk/issues/1047.
> **Note**
[^2]: _While we aim for automated …
=> [#1047][#1140] Improve CBD internal state handling

.github/workflows/pull-request.yml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/ExceptionExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/OpenEndRangeExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/WalletService.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/BlockHeight.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/ext/ExceptionExtTest.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/BlockHeightTest.kt
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1139, https://github.com/zcash/zcash-android-wallet-sdk/issues/1138.
- This makes the new subtask functions more testable.
> **Note**
something …
=> [#1139][#1138] Process Priority.Verify blocks

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transactions.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1148.
> **Note** …
=> [#1148] Improve Memo Querying Log

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transactions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1108.
> **Note** …
=> [#1108] Getting memo for sent transactions

CHANGELOG.md, gradle.properties
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1152.
> **Note** …
=> [#1152] SDK Release 1.20.0-beta01

.github/workflows/pull-request.yml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/OpenEndRangeExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ScanRange.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/ZcashNetwork.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/ZcashNetworkTest.kt
- It also better handles setState calls
- It fixes OpenEndRange -> ClosedRange
- And it improves logging in syncing mechanism
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1133
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you had to manually test …
=> [#1133] Set the correct getSubtreeRoots inputs

CHANGELOG.md, README.md, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1160.
> **Note** …
=> [#1160] New Sync Algorithm Type API

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1157.
> **Note** …
=> [#1157] Get roots: recover failed communication

CHANGELOG.md, README.md, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Navigation.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listtransactions/ListTransactionsFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/listutxos/ListUtxosFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/send/SendFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/fixture/WalletSnapshotFixture.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/view/HomeView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1129
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1164
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1165
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1166
> **Note**
[^2]: _While we aim for automated …
=> [#1129] Refactor ProcessorInfo

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Navigation.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/balance/view/BalanceView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transactions.kt, demo-app/src/main/res/values/strings.xml, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt
- This only solves manual polling of transactions and balances within the Demo app.
- Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1111.
- A more reactive solution that would provide automatic flows emitting and which would be part of the SDK is filed as a follow-up to this https://github.com/zcash/zcash-android-wallet-sdk/issues/1170.
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making …
=> [#1111] Poll transactions and balances while syncing

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt
Closes https://github.com/zcash/zcash-android-wallet-sdk/issues/1181
> **Note** …
=> [#1181] Do Not Update Transparent Balance Before `updateChainTip`

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
- This enables the balance flows feeding on the `CompactBlockProcessor` side. The balances are refreshed every 100 synced blocks, as the batch of blocks for synchronization was changed from 10 to 100. It can be optimized anytime further.  The changed batch size has a synchronization speed-up impact too. The synchronization is about one-third faster now.
- Although https://github.com/zcash/librustzcash/issues/900 will provide more accurate information for balances, this partly solves the issue https://github.com/zcash/zcash-android-wallet-sdk/issues/1170 as well. This is a prerequisite for that.
- Closes #1109 
- Closes #1206
> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of …
=> [#1109][#1206] Regular balance flows emission

CHANGELOG.md, README.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/WalletCoordinatorFactory.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/GetSubtreeRootsResult.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessorTest.kt
=> [#1210] Eliminate `LINEAR` sync support

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/GetMaxScannedHeightResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SyncingResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/BlockTable.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ScanProgress.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> [#1213] Remove `BlockTable` and its APIs

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Derivation.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniScanProgress.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ComposeActivity.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/SharedViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/PersistableWallet.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SdkSynchronizerTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/BalancePrinterUtil.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/DataDbScannerUtil.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
- Closes #1208
- Closes #1215
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases …
=> [#1208][#1215] Pass proper `recoverUntil`

darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/TransparentIntegrationTest.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/InboundTxTests.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/ReorgSetupTest.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/ReorgSmallTest.kt, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/DarksideTestCoordinator.kt
=> [#1225] Disable deprecated darkside tests

sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/BatchSyncProgress.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SbSPreparationResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/BlockBatch.kt
=> [#1219] Remove calculated sync progress

CHANGELOG.md, gradle.properties
- Library version bumped
- Changelog updated
- Closes #1229
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool …
=> [#1229] SDK Release 1.21.0-beta01

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt
=> [#1231] GetConsensusBranchId work with chain tip

CHANGELOG.md, gradle.properties
=> Update version & changelog for 2.0.0-rc.1 release.

.github/workflows/deploy-release.yml, .github/workflows/deploy-snapshot.yml
=> Extend the timeout for upload to Maven repositories to 10 minutes

sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ScanRange.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/ScanRangeTest.kt
- Tests added
- Closes #1242
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases …
=> [#1242] ScanRange fails when no matching priority

backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils.rs, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/JniScanProgressTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/GetScanProgressResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/WalletService.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ScanProgress.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/BlockHeight.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/ScanProgressTest.kt
=> [#1239] Post-v2.0.0-rc1 cleanup

CHANGELOG.md, gradle.properties
=> [#1257] SDK Release v2.0.0-rc.2

CHANGELOG.md, gradle.properties
=> [#1261] SDK Release v2.0.0-rc.3

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, gradle.properties, rust-toolchain.toml
=> SDK Release v2.0.0-rc.4

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/seed/view/ConfigureSeedView.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/fixture/PersistableWalletFixture.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/PersistableWalletTest.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/PersistableWallet.kt
=> [#1095] PersistableWallet endpoint API

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/balance/view/BalanceView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletSnapshot.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ZcashSdk.kt
- Removed all uses of the incorrect 1000-ZAT fee as defined with  deprecated zip-313
- Default is now 10k zatoshi, the minimum defined by zip-317
- Changelog updated
- Closes  #1273
> **Note**
something during …
=> [#1273] 10_000-ZAT Miners fee

CHANGELOG.md, gradle.properties
=> [#1274] SDK release v2.0.1

CHANGELOG.md, gradle.properties
=> [#1289] SDK Release 2.0.2

CHANGELOG.md, gradle.properties
=> [#1295] SDK release v2.0.3

docs/Public APIs.md
=> [#1309] Update Public APIs doc

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> [#1316] Readable TxId on TransactionOverview

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt
=> [#1248] Clean up unused exceptions

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/send/view/SendView.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecString.kt
=> [#1315] Provide Locale to MonetarySeparators API

CHANGELOG.md, gradle.properties
=> [#1322] Release zcash-android-wallet-sdk 2.0.4

CHANGELOG.md, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/fixture/PersistableWalletFixture.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/PersistableWalletTest.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/fixture/WalletAddressFixture.kt
=> [#1348] Regenerate fixture wallet addresses

.github/actions/setup/action.yml, backend-lib/build.rs, gradle.properties, rust-toolchain.toml
Closes Electric-Coin-Company/zcash-android-wallet-sdk#317.
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can …
=> Migrate to Rust 1.75.0 and NDK 26.1.10909125

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt
These are being merged into a feature branch to ensure we don't accidentally release these changes early, because the unreleased Zcash Rust crates are not stable.
> **Note**
something during development of this …
=> Rust updates for SDK 2.1.0

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniScanSummary.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummary.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/fixture/JniAccountBalanceFixture.kt, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummaryTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SyncingResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ScanSummary.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/WalletSummary.kt
=> Performance and summary updates

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs
=> Final Rust dependency update for 2.0.5

backend-lib/src/main/rust/lib.rs, sdk-lib/build.gradle.kts, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/metrics/TraceScope.kt
These appear when collecting a "System Trace" via the Profiler tab in Android Studio.
> **Note**
[^3]: _While we are not looking for …
=> Add tracing to `CompactBlockProcessor` methods and Rust FFIs

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs, gradle.properties, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
=> Fix Rust crash when shielding

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/fixture/JniAccountBalanceFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/AccountBalance.kt
=> backend-lib: Expose `AccountBalance` fields across the FFI

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/fixture/WalletSnapshotFixture.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/balance/view/BalanceView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletSnapshot.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/sample/TransparentRestoreSample.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/fixture/WalletBalanceFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/AccountBalance.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/WalletBalance.kt
- Adds the Kotlin side changes for #1380
- Changed WalletBalance to contain these three fields: available, changePending, and valuePending, instead of total and available, and change the transparent flow to StateFlow<Zatoshi>, as we don't distinguish there.
- Related connected APIs changed
- Closes #1385
> **Note**
[^2]: _While we …
=> [#1385] Adopt `AccountBalance` fields in Kotlin layer

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Navigation.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ext/LightWalletEndpointExt.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/view/HomeView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/server/view/ServerView.kt, demo-app/src/main/res/values/strings.xml, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/LightWalletClient.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/LightWalletClientImpl.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/model/LightWalletEndpointInfoUnsafe.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/PersistableWallet.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/ConsensusBranchId.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/type/ServerValidation.kt
- This ensures that the SDK supports apps switching between different lightwalletd servers
- Synchronizer.validateServerEndpoint API added
- Demo app updated to leverage this new feature
- Closes #1393
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you …
=> [#1393] Support server switching

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ProposalUnsafe.kt, backend-lib/src/main/proto/proposal.proto, backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils.rs, darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/getbalance/GetBalanceFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/demos/send/SendFragment.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, gradle.properties, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecSend.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManagerImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Proposal.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionSubmitResult.kt
`Synchronizer.sendToAddress` and `Synchronizer.shieldFunds` are deprecated, ahead of removal in SDK 2.1.0.
Closes Electric-Coin-Company/zcash-android-wallet-sdk#1359.
> **Note**
something during development of …
=> Expose APIs for working with transaction proposals

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/fixture/ZecSendFixture.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecSend.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecSendExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Proposal.kt
- Closes #1413
- This also enables serialization of the `Proposal` class 
> **Note**
[^3]: _While we are not looking …
=> [#1413] Update ZecSend with Proposal

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt
Closes Electric-Coin-Company/zcash-android-wallet-sdk#782.
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can …
=> Correctly throw `InitializeException.SeedRequired`

sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionSubmitResult.kt
=> [#1421] Improve TransactionSubmitResult

sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt
=> Update `TxOutputsView` to use correct column names.

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummary.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummaryTest.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/internal/LightWalletClientImpl.kt, lightwallet-client-lib/src/main/java/co/electriccoin/lightwallet/client/model/TreeStateUnsafe.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/CheckpointTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/jni/TransparentTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/CheckpointFixture.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/GetSubtreeRootsResult.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/Checkpoint.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TreeState.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/WalletSummary.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/ext/CheckpointExt.kt
Closes Electric-Coin-Company/zcash-android-wallet-sdk#528.
Closes Electric-Coin-Company/zcash-android-wallet-sdk#761.
> **Note**
[^3]: …
=> Integrate Orchard support

backend-lib/src/main/rust/lib.rs
This removes an `expect` call that risked crashing the app in the case of database corruption, potentially hiding other bugs.
> **Note** …
=> Return an error instead of a panic in the case of data corruption.

backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> Update to zcash_client_sqlite version 0.10.3

CHANGELOG.md, gradle.properties
=> [#1431] Release 2.1.0

sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/SQLiteDatabaseExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TransactionTable.kt
- These changes move database read accesses made from the Android side to the same dispatcher, `SdkDispatchers.DATABASE_IO`, which is shared with the Rust layer for writing accesses.
- All of the reading is done through `SupportSQLiteDatabase.queryAndMap` that has been changed
- Tested with many wallet restorations attempts on different Android SDK levels from 27-34.
- Closes #1440
> **Note**
>This code review checklist is intended to serve as a starting point for the author and review, altought it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).
[^1]: _Code often looks different when reviewing the …
=> [#1440] DB image malformed while scanning blocks

sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
This change avoids false-positives in clients
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out …
=> Improve logs stripping test

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils/exception.rs, rust-toolchain.toml
=> Rust dependency updates

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt, sdk-lib/src/test/java/cash/z/ecc/android/sdk/ext/ConversionsTest.kt
=> [#1455] Remove hard-coded currency decimal sep

CHANGELOG.md
=> [#1464] Release 2.1.1

CHANGELOG.md, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/DatabaseCoordinator.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt
=> [#1470] Add APIs to provide clearing of SDK data

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/server/view/ServerView.kt
=> [#1471] Add new LWD servers to Demo app

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/addresses/view/AddressesView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/TransactionsView.kt
=> [#1491] Adopt latest SDK changes within Demo app

.github/workflows/deploy-snapshot.yml, .gitignore, LICENSE, build-conventions/src/main/kotlin/zcash-sdk.publishing-conventions.gradle.kts, docs/PUBLISHING.md, gradle.properties
- Ultimately, we could merge the snapshot and release workflow files
- Addresses #1506
> **Note**
[^3]: _While we are not looking for …
=> [#1506] Sonatype Maven Central authentication issue

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs, rust-toolchain.toml
=> Rust updates and cleanups

CHANGELOG.md, docs/PUBLISHING.md
- Closes #1377
- This includes a minor documentation improvement, too
> **Note** …
=> [#1377] Release SDK v2.1.2

demo-app/lint-baseline.xml, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transaction.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/TransactionsView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/util/TransactionOverviewExt.kt, demo-app/src/main/res/values/strings.xml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt
=> ISSUE-1253 Transaction composable implementation

demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ext/LightWalletEndpointExt.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/server/view/ServerView.kt
=> [#1525] Demo app change default server

CHANGELOG.md
- Closes #1377
- Reattempted to release the SDK version 2.1.2 as the previous attempt failed due to #1506
> **Note**
[^3]: _While we are …
=> [#1377] Release zcash-android-wallet-sdk 2.1.2

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/WalletAddress.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManagerImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/type/AddressType.kt
=> ZIP 320 (TEX address) support

gradle.properties, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt
- So we’re able to consume unreleased snapshot versions within clients
- Unrelated: Added link to issue to the codebase 
> **Note** …
=> Change SDK library version to 2.1.3

sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/AllTransactionView.kt
- This is related only to `firstUnenhancedHeight` query in `v_transactions`
- Eventually closes #1536, the mentioned darkside test can be done after https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1224
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If …
=> [#1536] Proper sort null mined_height

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SyncingResult.kt
=> [#1483] Fetch UTXOs before scanning subphase

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/ext/ClosedRangeExt.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/BlockBatch.kt
Closes #1365
Sync speed results
---
**New wallet (cca 22K blocks):**
_Before_:
1. 14:15:53.199 - 14:09:02.966 = 6 minutes, 50 seconds, and 233
2. 14:24:15.356 - 14:18:32.068 = 5 minutes, 43 seconds, and 288
_After_:
1. 14:01:34.786 - 13:55:54.256 = 5 minutes, 40 seconds, and 530
2. 15:18:51.461 - 15:14:26.988 = 4 minut, 24 sekund a 473
**Wallet restoration (cca 117K blocks):**
_Before:_
16:32:09.854 - 16:02:00.592 = 30 minut, 9 sekund a 262
_After:_
15:51:07.254 - 15:22:28.317 = 28 minut, 38 sekund a 937
> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please …
=> [#1365] Raise sync batch size outside of sandblasting to 1000

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/block/FileCompactBlockRepository.kt
- Closes #1364
- Filed another related improvement issue #1555
- The implemented changes still work well for the sandblasting period, too, where we sync batch of 100 blocks.
Block synchronization tests results:
---
**Restore older wallet (122K blocks):**
_Before:_
10:04:18.586 - 09:39:49.527 = 00:24:29
_After:_
10:20:13.480 - 10:07:22.831 = 00:12:50
= **cca -48.5%**
**New wallet: (2.5K blocks):**
_Before:_
10:41:23.064 - 10:40:47.286 = 00:00:35.778
_After:_
10:44:26.194 - 10:44:07.951 = 00:00:18.000000
= **cca -50%** 
> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we …
=> [#1364] Increase BLOCKS_METADATA_BUFFER_SIZE

CHANGELOG.md
=> [#1514] Release 2.1.3

CHANGELOG.md, gradle.properties
=> [#1394] Release 2.2.0

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, gradle.properties
This release fixes a database migration error that could cause a problem with wallet upgrade in some existing wallets.
> **Note**
[^3]: …
=> release zcash-android-wallet-sdk version 2.2.1

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> Remove SQL that can only run on newer SQLite

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/send/view/SendView.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/util/TransactionOverviewExt.kt, gradle.properties, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/FiatCurrencyConversionRateStateTest.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/ZatoshiExtTest.kt, sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/ZecStringTest.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/FiatCurrencyConversionExt.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/Locale.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZatoshiExt.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecSendExt.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/ZecString.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/FiatCurrency.kt
=> [#1579] Zec/Fiat conversion APIs accept Locale

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/FastestServerFetcher.kt
=> Fastest server estimated height valuation

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TorClient.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/exchange/UsdExchangeRateFetcher.kt
- These changes attempt to solve https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1587 by improving concurrent access to the Rust Tor client by adding mutex and closure into `TorClient` and `TorClientHolder`. The PR also adds clearing of references after the disposal.
- But the crash, as described in #1587, is still reproducible. 
> **Note**
[^1]: _Code often looks different when reviewing the diff …
=> Fix tor access

gradle.properties
- To enable clients to consume the new snapshot version
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can …
=> Bump SDK library version to 2.2.5

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt
- These changes also move the verifySetup trigger before refreshUtxos at the beginning of the Synchronizer start
- Closes #1127
- Note: We will merge this PR quickly to evaluate the new SDK snapshot behavior on the impacted user device. We'll address any comments or potential unsuccessful fix in a follow-up ticket.
> **Note** …
=> [#1127] Refactor `CompactBlockProcessor.verifySetup`

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt
=> [#1609] FailedSynchronizationException full stacktrace

CHANGELOG.md
=> [#1614] Release 2.2.5

demo-app/build.gradle.kts
- As part of this change, we ensured that the proguard is turned off for the production library version
- This is part of https://github.com/Electric-Coin-Company/zashi-android/issues/1656
> **Note**
something …
=> Remove unnecessary shrink resources

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOutput.kt
=> Transaction outputs API

sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/internal/DerivationToolImplTest.kt
=> ZIP32 test vectors

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/rust/lib.rs
This updates to use `librustzcash` releases:
* zcash_primitives 0.20
* zcash_proofs 0.20
* zcash_keys 0.5
* zcash_client_backend 0.15
* zcash_client_sqlite 0.13
Other updated dependencies:
* rusqlite 0.32
* tor-rtcompat 0.23
> **Note**
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If …
=> Update transaction proposal creation to use `MultiOutputChangeStrategy`

gradle.properties
=> Bump library version to 2.2.6

backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/utils.rs
Instead of requiring the caller to provide a closure to construct a dummy element, we use the value for index 0 (or `null` in the case of an empty array) as the `initial_element`.
> **Note**
something during …
=> Simpler API for `rust_vec_to_java`

sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManager.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/OutboundTransactionManagerImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt
- These changes remove unused SDK internal `TransactionEncoder` functions that were used by previously removed  deprecated functions `Synchronizer.sendToAddress` and `Synchronizer.shieldFunds` in https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1645
> **Note**
[^2]: _While we aim for automated testing of the …
=> Remove unused `TransactionEncoder` functions

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt
=> Add `getAccountForUfvk`  method to Rust backend & fix key derivation null issue.

CHANGELOG.md, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/exception/Exceptions.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Pczt.kt
=> PCZT support follow-ups

backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt
=> Fix import account parameter

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt
=> Get trx by memo substring

gradle.properties
=> Bump SDK library version to 2.2.8

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/fixture/TransactionOverviewFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DbDerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/repository/DerivedDataRepository.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/PendingTransaction.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionId.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
- And used instead of `FirsClassByteArray` in several APIs
- Changelog
- Closes #1676
> **Note**
[^3]: _While we are not looking for …
=> [#1676] Introduce `TransactionId`

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/PendingTransaction.kt
=> Hotfix for fetching recipients of an account existing in database

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/fixture/TransactionOverviewFixture.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/AllTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/DbTransactionOverview.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> Transaction fields propagation

gradle.properties
=> [#1709] Library version 2.2.9

.github/workflows/pull-request.yml
Until #1326 is resolved
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that …
=> [#1326] Disable broken `test_robo_demo_app`

sdk-lib/build.gradle.kts, sdk-lib/src/androidTest/java/cash/z/ecc/preference/MockPreferenceProvider.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/fixture/BooleanPreferenceDefaultFixture.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/fixture/IntegerPreferenceDefaultFixture.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/fixture/StringDefaultPreferenceFixture.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/model/entry/BooleanPreferenceDefaultTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/model/entry/IntegerPreferenceDefaultTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/preference/model/entry/StringPreferenceDefaultTest.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/AndroidPreferenceProvider.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/EncryptedPreferenceProvider.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/PreferenceHolder.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/StandardPreferenceProvider.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/api/PreferenceProvider.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/keys/EncryptedPreferenceKeys.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/keys/StandardPreferenceKeys.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/model/entry/BooleanPreferenceDefault.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/model/entry/IntegerPreferenceDefault.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/model/entry/PreferenceDefault.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/model/entry/PreferenceKey.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/model/entry/StringPreferenceDefault.kt
=> [#1715] SDK `SharedPreferences`

sdk-lib/build.gradle.kts, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/preference/keys/StandardPreferenceKeys.kt
The new trigger tested using the Demo app.
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out …
=> Check and trigger `backend.fixWitnesses`

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> Update to released version of the `librustzcash` crates.

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/model/SyncingResult.kt
- As discussed internally with @nuttycom, fetching UTXOs in the sync on-init and on-complete callbacks is sufficient with the current Rust logic state.
- Closes #1552 
> **Note**
something …
=> [#1552] Fetch UTXOs less frequently

backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> Bump `zcash_client_sqlite` to v0.16.1

gradle.properties
=> Bump library version to 2.2.10

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml
=> Update to zcash_client_sqlite-0.16.2

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, gradle.properties
=> Library version 2.2.11

CHANGELOG.md
=> [#1734] Release v2.2.11

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ComposeActivity.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/seed/view/ConfigureSeedView.kt, demo-app/src/main/res/values/strings.xml, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/Checkpoint.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/tool/CheckpointTool.kt
- Closes #1730
- The demo app is only the simplest new API adoption
> **Note**
[^3]: _While we are not looking for …
=> [#1730] Estimate Wallet Birthday from date

gradle.properties
=> Bump library version to 2.2.12

CHANGELOG.md
=> [#1748] SDK Release 2.2.12

CHANGELOG.md, backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/test/java/cash/z/ecc/android/sdk/internal/model/JniWalletSummaryTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/UnifiedAddressRequest.kt
=> Add the ability for SDK users to request unified addresses with custom receiver types.

backend-lib/Cargo.lock, backend-lib/Cargo.toml, backend-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/jni/TorClientTest.kt, backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TorClient.kt, backend-lib/src/main/rust/lib.rs, backend-lib/src/main/rust/tor.rs, sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
=> Migrate to `zcash_client_sqlite 0.17`

CHANGELOG.md, gradle.properties
=> SDK Release 2.2.14

CHANGELOG.md, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/SharedViewModel.kt, demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/WalletCoordinatorFactory.kt, sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/WalletCoordinator.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/SdkSynchronizerTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/BalancePrinterUtil.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/processor/CompactBlockProcessor.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/SdkFlags.kt
=> Exchange rate and tor decoupled

darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt, demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/DataDbScannerUtil.kt, sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt
=> Test hotfixes

CHANGELOG.md, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/AllTransactionView.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/DbTransactionOverview.kt, sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/TransactionOverview.kt
=> Column expired_unmined in v_transactions propagated to transaction state

backend-lib/Cargo.lock, backend-lib/Cargo.toml
This ensures that fully transparent transactions that are added to the wallet as a consequence of mempool scanning are subsequently checked to determine when they are mined into a block.
> **Note**
something …
=> Update to `librustzcash 88a6423088d84fb01e2ed24b59dae1519e8de94c`
